name: WellnessTourism-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-train-evaluate-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        python src/preprocessing.py
        
    - name: Train model
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python src/train.py
      
    - name: Evaluate model
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python src/evaluate.py

    - name: Upload experiment logs
      uses: actions/upload-artifact@v4
      with:
        name: experiment-logs
        path: logs/experiment_log.json

    - name: Upload evaluation metrics
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-metrics
        path: models/evaluation_metrics.txt
    
    - name: Build Docker image
      run: |
        docker build -t wellness-tourism:latest -f Dockerfile .

    - name: Push model to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        python src/deploy.py
        
    - name: Deploy to Hugging Face Space (Docker SDK)
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install "huggingface_hub[cli]"
        huggingface-cli upload Murali0606/WellnessTourism Dockerfile Dockerfile --repo-type space --token $HF_TOKEN
        huggingface-cli upload Murali0606/WellnessTourism app.py app.py --repo-type space --token $HF_TOKEN
        huggingface-cli upload Murali0606/WellnessTourism requirements.txt requirements.txt --repo-type space --token $HF_TOKEN
        huggingface-cli upload Murali0606/WellnessTourism src src --repo-type space --token $HF_TOKEN
