name: WellnessTourism-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-train-evaluate-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt

    - name: Run preprocessing
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        python src/preprocessing.py
        
    - name: Train model
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python src/train.py
      
    - name: Evaluate model
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python src/evaluate.py

    - name: Build Docker image
      run: |
        docker build -t wellness-tourism:latest -f docker/Dockerfile .

    - name: Push model to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        python src/deploy.py
        
    - name: Deploy to Hugging Face Space (Docker SDK)
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install "huggingface_hub[cli]"
        huggingface-cli upload Murali0606/WellnessTourism docker/Dockerfile docker/Dockerfile --repo-type space --token $HF_TOKEN
        huggingface-cli upload Murali0606/WellnessTourism docker/app.py docker/app.py --repo-type space --token $HF_TOKEN
        huggingface-cli upload Murali0606/WellnessTourism docker/requirements.txt docker/requirements.txt --repo-type space --token $HF_TOKEN
        huggingface-cli upload src --repo Murali0606/WellnessTourism --repo-type space --token $HF_TOKEN
